# Generated by Django 2.1.7 on 2019-04-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovohotPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picname', models.CharField(max_length=40)),
                ('src', models.CharField(max_length=100)),
                ('picstore', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'novohot_pic',
            },
        ),
        migrations.CreateModel(
            name='NovohotTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'novohot_tag',
            },
        ),
        migrations.CreateModel(
            name='NovohotTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('titletag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novohot.NovohotTag')),
            ],
            options={
                'db_table': 'novohot_title',
            },
        ),
        migrations.AddField(
            model_name='novohotpic',
            name='pictitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novohot.NovohotTitle'),
        ),
    ]
