# Generated by Django 2.1.7 on 2019-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novohot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novohotpic',
            name='picname',
            field=models.CharField(max_length=100),
        ),
    ]
