# Generated by Django 2.1.7 on 2019-04-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novohot', '0002_auto_20190404_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novohotpic',
            name='picstore',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='novohotpic',
            name='src',
            field=models.CharField(max_length=200),
        ),
    ]
