# Generated by Django 2.1.7 on 2019-03-24 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sgrade',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Myapp.Grades'),
        ),
    ]
