# Generated by Django 2.1.7 on 2019-03-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_student_sgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='gboynum',
            field=models.IntegerField(verbose_name='男生人数'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='gdate',
            field=models.DateField(verbose_name='年 份'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='ggirlnum',
            field=models.IntegerField(verbose_name='女生人数'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='gname',
            field=models.CharField(max_length=20, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='student',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sage',
            field=models.IntegerField(verbose_name='年  龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='scontent',
            field=models.CharField(max_length=20, verbose_name='简  介'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sgender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=30, verbose_name='性  别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sgrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Grades', verbose_name='班 级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=20, verbose_name='姓  名'),
        ),
    ]
