# Generated by Django 2.1.7 on 2019-06-15 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YuvideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'yuvideo_tag',
            },
        ),
        migrations.CreateModel(
            name='YuvideoVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(max_length=100)),
                ('src', models.URLField(max_length=100)),
                ('mp4href', models.URLField(max_length=100)),
                ('videotag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuvideo.YuvideoTag')),
            ],
            options={
                'db_table': 'yuvideo_video',
            },
        ),
    ]
