# Generated by Django 2.1.7 on 2019-03-27 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meituxiu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeituPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picname', models.CharField(max_length=40)),
                ('src', models.CharField(max_length=100)),
                ('picstore', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'meitu_pic',
            },
        ),
        migrations.CreateModel(
            name='MeituTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'meitu_tag',
            },
        ),
        migrations.CreateModel(
            name='MeituTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('titletag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meituxiu.MeituTag')),
            ],
            options={
                'db_table': 'meitu_title',
            },
        ),
        migrations.DeleteModel(
            name='Meitu',
        ),
        migrations.AddField(
            model_name='meitupic',
            name='pictitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meituxiu.MeituTitle'),
        ),
    ]
