# Generated by Django 2.1.7 on 2019-05-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MmonlyPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picname', models.CharField(max_length=50)),
                ('src', models.URLField(max_length=100)),
            ],
            options={
                'db_table': 'mmonly_pic',
            },
        ),
        migrations.CreateModel(
            name='MmonlyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mmonly_tag',
            },
        ),
        migrations.CreateModel(
            name='MmonlyTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('titletag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmonly.MmonlyTag')),
            ],
            options={
                'db_table': 'mmonly_title',
            },
        ),
        migrations.AddField(
            model_name='mmonlypic',
            name='pictitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmonly.MmonlyTitle'),
        ),
    ]
