# Generated by Django 2.1.7 on 2019-05-11 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mm8Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picname', models.CharField(max_length=50)),
                ('src', models.URLField(max_length=100)),
            ],
            options={
                'db_table': 'mm8_pic',
            },
        ),
        migrations.CreateModel(
            name='Mm8Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mm8_tag',
            },
        ),
        migrations.CreateModel(
            name='Mm8Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('titletag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm8.Mm8Tag')),
            ],
            options={
                'db_table': 'mm8_title',
            },
        ),
        migrations.AddField(
            model_name='mm8pic',
            name='pictitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm8.Mm8Title'),
        ),
    ]
