# Generated by Django 2.1.7 on 2019-03-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='姓  名')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生  日')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=30, verbose_name='性  别')),
                ('account', models.IntegerField(default=0, verbose_name='ID 号')),
                ('age', models.IntegerField(default=60, verbose_name='年  龄')),
            ],
        ),
    ]
