# Generated by Django 2.1.7 on 2019-04-18 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeituriPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picname', models.CharField(max_length=50)),
                ('src', models.URLField(max_length=100)),
            ],
            options={
                'db_table': 'meituri_pic',
            },
        ),
        migrations.CreateModel(
            name='MeituriTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'meituri_tag',
            },
        ),
        migrations.CreateModel(
            name='MeituriTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('titletag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meituri.MeituriTag')),
            ],
            options={
                'db_table': 'meituri_title',
            },
        ),
        migrations.AddField(
            model_name='meituripic',
            name='pictitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meituri.MeituriTitle'),
        ),
    ]
