# Generated by Django 2.1.7 on 2019-05-26 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zhuamei5Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picname', models.CharField(max_length=50)),
                ('src', models.URLField(max_length=100)),
            ],
            options={
                'db_table': 'zhuamei5_pic',
            },
        ),
        migrations.CreateModel(
            name='Zhuamei5Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'zhuamei5_tag',
            },
        ),
        migrations.CreateModel(
            name='Zhuamei5Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('titletag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhuamei5.Zhuamei5Tag')),
            ],
            options={
                'db_table': 'zhuamei5_title',
            },
        ),
        migrations.AddField(
            model_name='zhuamei5pic',
            name='pictitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhuamei5.Zhuamei5Title'),
        ),
    ]
